name: Dynamic Secrets
on: push
env:
  one: onevalue
  two: twovalue
  three: threevalue

jobs:
  job0:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ env.one }}"
          echo "${{ env.two }}"
          echo "${{ env.three }}"

  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=$(date +"%d-%m-%Y")-asdfads223" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
